const NOTIFICATION_TYPES = {
  // User Registration Flow
  NEW_USER_REQUEST: "NEW_USER_REQUEST",
  USER_APPROVED: "USER_APPROVED",
  USER_REJECTED: "USER_REJECTED",

  // Patient Workflow
  PATIENT_REGISTERED: "PATIENT_REGISTERED",
  PATIENT_CHECKIN: "PATIENT_CHECKIN",
  PATIENT_ADMITTED: "PATIENT_ADMITTED",
  PATIENT_CHECKOUT: "PATIENT_CHECKOUT",

  // Appointment
  APPOINTMENT_BOOKED: "APPOINTMENT_BOOKED",
  APPOINTMENT_CANCELLED: "APPOINTMENT_CANCELLED",
  APPOINTMENT_RESCHEDULED: "APPOINTMENT_RESCHEDULED",

  // Lab
  TEST_REQUEST_CREATED: "TEST_REQUEST_CREATED",
  TEST_REPORT_READY: "TEST_REPORT_READY",

  // Billing
  INVOICE_GENERATED: "INVOICE_GENERATED",
  PAYMENT_SUCCESS: "PAYMENT_SUCCESS",

  // Emergency
  EMERGENCY_ALERT: "EMERGENCY_ALERT",

  // Messaging
  NEW_CHAT_MESSAGE: "NEW_CHAT_MESSAGE",

  // Doctor Workflow
  DOCTOR_LATE_CHECKIN: "DOCTOR_LATE_CHECKIN",
  NEW_PATIENT_ASSIGNED: "NEW_PATIENT_ASSIGNED",
};


export default NOTIFICATION_TYPES;